signalfx/splunk-otel-ios

README.md
SplunkRumWorkspace/SplunkRum/SplunkRum/LimitingExporter.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/UtilsTests.swift

It can now modify the span and has a simpler semantics for remebering how to
drop a span (return nil instead of... true? like before).

Switch spanRejectionFilter for more flexible spanFilter

---

SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift

A problem with AFNetworking 2.5.3 occured where nil was passed as the URL,
which was not representable with the Swift struct URL but is representable
with the (proper) NSURL*(ObjC) / NSURL(Swift) type, which, as a pointer, is nil-able.

Use proper NSURL type for network instrumentation

---

SplunkRumWorkspace/SplunkRum/SplunkRum/AppStart.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/UIInstrumentation.swift

- was erroneously marked as "manually set" when automatically set
- was not using app.keyWindow which is best source; top-most window used as fallback

Fix screen name

---

SplunkRumWorkspace/SmokeTest/SmokeTest/Info.plist
SplunkRumWorkspace/SmokeTest/SmokeTest/ViewController.swift
SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
SplunkRumWorkspace/SplunkRum/SplunkRum.xcodeproj/project.pbxproj
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/WebViewInstrumentation.swift

- Introduces SplunkRum.integrateWithBrowserRum(webkitView)
- Exposes the native session ID through javascript method
window.SplunkRumNative.getNativeSessionId()
- Smoke test with a convoluted path to verifying this behavior

Instrument WebKit to integrate with browser RUM

---

Package.swift
SplunkRumWorkspace/SplunkRum/SplunkRum.xcodeproj/project.pbxproj
SplunkRumWorkspace/SplunkRumWorkspace.xcworkspace/xcshareddata/swiftpm/Package.resolved

Mainly due to https://github.com/open-telemetry/opentelemetry-swift/pull/306, but there are additional fixes: https://github.com/open-telemetry/opentelemetry-swift/releases

upgrade to OTel 1.1.4

---

README.md
SplunkRumWorkspace/SplunkRum/SplunkRum/SpanToDiskExporter.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
SplunkRumWorkspace/SplunkRum/SplunkRumDiskExportTests/DiskExportCommon.swift
SplunkRumWorkspace/SplunkRum/SplunkRumDiskExportTests/DiskExportPipelineTest.swift
SplunkRumWorkspace/SplunkRum/SplunkRumDiskExportTests/SpanFromDiskExporterTest.swift

* Expose setting the span disk cache size to users.
* Set the default disk cache size to 25 MB to be in line with the Android SDK.
* Reduce truncation checkpoint (the count of inserted spans after which a check for database size is done) from 2048 to 512.

feat: make span disk cache size configurable

---

SplunkRumWorkspace/SmokeTest/SmokeTest/Base.lproj/Main.storyboard
SplunkRumWorkspace/SmokeTest/SmokeTest/ViewController.swift
SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
SplunkRumWorkspace/SplunkRum/SplunkRum.xcodeproj/project.pbxproj
SplunkRumWorkspace/SplunkRum/SplunkRum/SlowFrameDetector.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift

Changes: with signed commits.
Pause CADisplayLink when on app will resign and resume it on app activation. Simplifies the code somewhat and avoids issues with counting the frame duration when the app is moved to background.
Group slow and frozen frames per screen names. This is necessary so when 2 different screens have a slow frame in a second interval, they are both reported.
Use screen name callbacks to store the screen name locally to avoid the locking in getScreenName()
Use a 1 second timer to periodically dump the detected frames.

APMI-2306 slow and frozen frame detection

---

SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkType.swift

Switching from cellular to wifi did not clear carrier information.

fix: clear carrier info on non-cell connection types

---

.swiftlint.yml
SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkType.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift

CI had it's swiftlint upgraded, which started failing on the current codebase due to `orphaned_doc_comment` rule (https://github.com/signalfx/splunk-otel-ios/actions/runs/3477866164/jobs/6009506623#step:3:40).
This rule was triggered when there was a doc comment before a function that had a `swiftlint:disable:next` clause for a different rule. E.g. `SplunkRum.initialize` had `//swiftlint:disable:next cyclomatic_complexity`.
Added `cyclomatic_complexity` to ignored rules, don't think it's useful anyway.

chore: disable cyclomatic_complexity lint rule

---

SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift

Adds the @ discardableResult annotation to the SplunkRum.initialize call. 
This gets rid of the warning seen here for those library consumers that do not want to /need to pay attention to the result of the initialize call (including the sample apps).
Some projects are also setup to have warnings be errors which means you have to handle the result value which means you end with code like: 
```swift
_ = SplunkRum.initialize(...)
```

SplunkRum.initialize discardable result

---

SplunkRumWorkspace/SplunkRum/SplunkRum/AppLifecycle.swift

RUM doing a “forceFlush” in the main thread and that is taking longer than what iOS/Apple allows

POR-14136 RUM instrumentation is causing crashes because of forceFlush

---

SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift
SplunkRumWorkspace/TestApp/TestApp/ContentView.swift

📄 https://github.com/signalfx/splunk-otel-ios/issues/106
As other SDKs (e.g. Sentry) have had the same problem and have already fixed it, this translation to Swift is based on
https://github.com/getsentry/sentry-cocoa/blob/8.0.0/Sources/Sentry/SentryNSURLSessionTaskSearch.m (which is based on code from AFNetworking)
and https://github.com/getsentry/sentry-cocoa/blob/8.0.0/Sources/Sentry/SentryNetworkTracker.m
I've removed locking code around `objc_getAssociatedObject` and `objc_setAssociatedObject` as internally they seem to use global (!?) locking: https://github.com/opensource-apple/objc4/blob/master/runtime/objc-references.mm#L221
NOTE: The PR is against an experimental branch

feat: network instrumentation without KVO

---

Package.swift
SplunkRumWorkspace/SplunkRum/SplunkRum.xcodeproj/project.pbxproj
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/NetworkInstrumentationTests.swift
SplunkRumWorkspace/SplunkRumWorkspace.xcworkspace/xcshareddata/swiftpm/Package.resolved

Pins the open-telemetry-swift version to 1.2.0 so that 1.4.0 is not pulled in which has a breaking change.

Pinning open telemetry swift to exact 1.2.0 for breaking change in 1.4.0

---

.github/workflows/ci.yml
.swiftlint.yml
SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkType.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/OpenTelemetry/OpenTelemetryApi/OpenTelemetry.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/OpenTelemetry/OpenTelemetrySdk/Trace/AttributesDictionary.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/OpenTelemetry/OpenTelemetrySdk/Trace/RecordEventsReadableSpan.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/UIInstrumentation.swift
dependencies.txt

Mainly to bring in https://github.com/open-telemetry/opentelemetry-swift/pull/379

chore: update opentelemetry swift

---

SplunkOtel.podspec
SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
fullbuild.sh

Same as https://github.com/signalfx/splunk-otel-ios/pull/142 but remade as I had to mess with my SSH keys and it unverified my commits.
Creates the podspec file for cocoapods support.
Adds a version check in the fullbuild script to ensure the version number on the Swift Package and Cocoapod is the same. 
Removes a broken lint check in the UI test that was preventing the build from completing.

MOB-3105 Creates Podspec File for Cocoapods Support

---

.github/CODEOWNERS

Adding myself and @seemk as Codeowners. Once we turn on the Require Code Owners branch protection, a code owner will need to approve all PRs before it gets merged.
Siim, let me know if you don't actually want to be a codeowner and I can take you off. Having 3 seemed like a good idea so one of us can take an extended vacation without holding up the other codeowner's PRs

Adding Codeowners

---

README.md

Updates the README with new badges and a link to the troubleshooting doc

Dvernon/MOB-3251 Update Readme

---

.github/CODEOWNERS

Updates the codeowners file to point to the gdi-ios-maintainers team instead of individuals to comply with GDI specs. I just updated the teams so previous codeowners will not lose access.

MOB-3281 - Update Codeowners

---

SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/ServerTimingTests.swift

Fixes the parse on reading the traceparent so it will work even if "traceparent" isn't the first pattern in the string. Also cleaned up the syntax to make it a bit more "swifty" and remove some nested ifs.

Dvernon/MOB-3294 Parsing traceparent

---

SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SessionBasedSampler.swift
SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/SessionSamplingTests.swift

We are having some crashes that are being tracked on Crashlytics. Based on the stack trace, it appears that Splunk is attempting to change the sampler during session changes. I suspect that there are spans that are referencing the old sampler while Splunk is replacing them.
This pull request eliminates the constant need to replace samplers, as everything is now handled within the SessionBasedSampler class.
**Crash stack trace:**
```
Crashed: scheduler-thread
0  libsystem_kernel.dylib         0x7578 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7118 pthread_kill + 268
2  libsystem_c.dylib              0x1d178 abort + 180
3  libswiftCore.dylib             0x3b8b98 swift::fatalError(unsigned int, char const*, ...) + 134
4  libswiftCore.dylib             0x3b8bb8 …
```

Implement Sampler protocol for SessionBasedSampler

---

.github/workflows/ci.yml

Adds Lychee link checker and Codecov to the repo to be run with each build. GDI spec recommends these two apps on its repos.

MOB-3278 Lychee and Codecov

---

.github/CODEOWNERS
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
SECURITY.md

based on gdi-spec 1.6.0
Needed for https://github.com/signalfx/gdi-specification/issues/255

Update required files

---

RELEASING.md

Adds a RELEASING.md for gdi compliance.

Adding RELEASING.md

---

.swiftlint.yml

... we can always turn it back on later if desired.  This is a new behavior with a new version of swiftlint and it is causing builds to fail.

Disable swiftlint unneeded_override as default auto-generated code has it

---

SplunkRumWorkspace/SplunkRum/SplunkRum/SessionBasedSampler.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/SessionSamplingTests.swift

Use the session ID bytes for the source of randomness when making a sampling decision.
The algorithm for the session ID value calculation is the same as is in the [JS RUM SDK](https://github.com/signalfx/splunk-otel-js-web/blob/main/packages/web/src/SessionBasedSampler.ts#L88). This fixes the issue where, if sampling is used with the iOS SDK and inside a WebView, the SDKs come to a different sampling decision due to differing algorithms.
Note: session ID callbacks should have the session ID as a parameter, but this would be a breaking change in the public API, so I decided to keep the plain callbacks for now.

sampling: use session id for source of randomness

---

CHANGELOG.md

Looks like the podfile and SplunkRum.swift are already at 0.11.3

chore: update changelog / release 0.11.3

---

MRUM.xcworkspace/xcshareddata/swiftpm/Package.resolved
MRUMAgent/Sources/CiscoRUM/Agent/Events/Event Manager/DefaultEventManager.swift
MRUMAgent/Sources/CiscoRUM/Agent/Events/Events/SessionReplayDataEvent.swift
MRUMAgent/Sources/CiscoRUM/Agent/Modules/Pool/DefaultModulesPool.swift
MRUMAgent/Sources/CiscoRUM/Public API/CiscoRUMAgent.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Model Conversions/Preferences+Conversions.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Model Conversions/RecordingMask+Conversions.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Model Conversions/RenderingMode+Conversions.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Model Conversions/Status+Conversions.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Proxies/Module/SessionReplay+RecordingMask.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Proxies/Module/SessionReplay.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Proxies/Module/SessionReplayPreferences.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Proxies/Module/SessionReplaySensitivity.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Proxies/Module/SessionReplayState.swift
MRUMAgent/Sources/CiscoRUM/Public API/Modules/Session Replay/Public API/API-1.0-Sensitivity+UIView.swift
MRUMAgent/Tests/CiscoRUMTests/Agent/Events/EventsTests.swift
MRUMAgent/Tests/CiscoRUMTests/Public API/Modules/SessionReplay/API-1.0-TypeConversions.swift
MRUMAgent/Tests/CiscoRUMTests/Testing Support/Builders/SessionReplayTestBuilder.swift
MRUMSessionReplayProxy/Sources/MRUMSessionReplayProxy/SessionReplay+Module.swift

This PR integrates the latest Github Session Replay into the Agent.
It does by:
- Updating the develop branch tip
- Changing all imports from `MRUMSessionReplay` to `CiscoSessionReplay`
- Implementing the new SR data chunk API
The integration steps are described in [this section](https://splunk.atlassian.net/wiki/spaces/PROD/pages/1078720400564/Session+replay+integration+on+iOS#Current-(temporary)-integration-limitations).
Please note that even tho all changes should be in place, there is still not a 100% guarantee the project correctly builds due to the amount of compiler errors emitted also from the broken OTel integration. This will be tested when both branches are done.

Integrate Session Replay into the Agent

---

MRUM.xcworkspace/xcshareddata/swiftpm/Package.resolved
MRUMAgent/Tests/CiscoRUMTests/Agent/Resources/ResourcesTests.swift
MRUMNetwork/Sources/MRUMNetwork/NetworkInstrumentation.swift
MRUMOTel/Package.swift
MRUMOTel/Sources/MRUMOTel/Log Event Processor/OTLPLogEventProcessor+AgentEvent.swift
MRUMOTel/Sources/MRUMOTel/Log Event Processor/OTLPLogEventProcessor.swift
MRUMOTel/Sources/MRUMOTel/Resources/Resource+AgentResources.swift
MRUMOTel/Sources/MRUMOTel/Trace Processor/OTLPTraceProcessor.swift
MRUMOTel/Sources/MRUMOTel/Utils/AttributeValue+MrumEventAttributeValue.swift
MRUMOTelBackgroundExporter/Package.swift
MRUMOTelBackgroundExporter/Sources/MRUMOTelBackgroundExporter/Exporters/logs/OTLPBackgroundHTTPLogExporter.swift
MRUMOTelBackgroundExporter/Sources/MRUMOTelBackgroundExporter/Exporters/metric/OTLPBackgroundHTTPMetricExporter.swift
MRUMOTelBackgroundExporter/Sources/MRUMOTelBackgroundExporter/Exporters/trace/OTLPBackgroundHTTPTraceExporter.swift
MRUMOTelBackgroundExporter/Sources/MRUMOTelBackgroundExporter/Models/RequestDescriptor.swift
MRUMOTelBackgroundExporter/Sources/MRUMOTelBackgroundExporter/OTLPBackgroundHTTPBaseExporter.swift
MRUMSlowFrameDetector/Sources/MRUMSlowFrameDetector/ScreenName/ScreenManager.swift

This PR replaces old adhoc created opentelemetry-swift files by integrating the upstream opentelemetry-swift instead.

DEMRUM-1181 Integrate opentelemetry-swift upstream

---

SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
SplunkCrashReports/Sources/SplunkCrashReports/CrashReportConfig.swift
SplunkCrashReports/Sources/SplunkCrashReports/CrashReportDeviceStats.swift
SplunkCrashReports/Sources/SplunkCrashReports/CrashReportJSON.swift
SplunkCrashReports/Sources/SplunkCrashReports/CrashReportKeys.swift
SplunkCrashReports/Sources/SplunkCrashReports/CrashReports+Module.swift
SplunkCrashReports/Sources/SplunkCrashReports/CrashReports.swift

- Modified the Crash Report payload to match the new Splunk Crash Reporting data model
- Cleaned up unused names CrashReportKeys
- Added support for collecting device stats, from original splunk agent

DEMRUM-1226: Update Crash Report data model

---

SplunkRumWorkspace/SplunkRum/SplunkRum/LimitingExporter.swift
SplunkRumWorkspace/SplunkRum/SplunkRumTests/MiscTests.swift

Updated the MAX_ATTRIBUTE_LENGTH to 131072 in LimitingExporter.swift

DEMRUM-1939 Update attribute size limit

---

Applications/DevelApp/DevelApp/ContentView.swift
Splunk.xcworkspace/xcshareddata/swiftpm/Package.resolved
SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-Session.swift
SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-SessionState.swift
SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
SplunkAgent/Tests/SplunkAgentTests/Agent/Events/EventsTests.swift
SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-SessionTests.swift

This PR implements new `SessionState` container as per [these docs](https://splunk.atlassian.net/wiki/spaces/PROD/pages/1078750096708/iOS+agent+API#State) (the links in related ticket are wrong). Note that it does not implement the proposed constructor as it doesn't make contextual sense.
One thing to consider is the unification of docc of the `samplingRate` properties in `SessionState` and `AgentConfiguration`.

DEMRUM-1683: Implement SessionState and related logic

---

SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentationIgnoreURLs.swift
SplunkNetwork/Tests/SplunkNetworkTests/IgnoreURLsTests.swift

- Added IgnoreURLs class to manage Regex patterns supplied by users through the ignoreURLs API (The actual API support to be added in another ticket)
- Added code to stop instrumenting a url if it matches the supplied pattern
- Added unit tests

DEMRUM-772 Add IgnoreURLs support to Network Instrumentation

---

SplunkAgent/Sources/SplunkAgent/Agent/Events/Event Manager/DefaultEventManager.swift
SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Span Interceptor Exporter/SpanInterceptorExporter.swift
SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Stdout Exporters/SplunkStdoutSpanExporter.swift
SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Trace Processor/OTLPTraceProcessor.swift

This PR implements the internals for the already existing public API of the customer-allowed span interception.
It also refactors the `SplunkStdoutSpanExporter` to live in the exporter chain, to correctly log all span data from the whole pipeline.

DEMRUM-938: Implement span interception internals

---

Applications/DevelApp/DevelApp/AgentDataSource.swift
Applications/DevelApp/DevelApp/SessionReplayDemoView.swift
SplunkAgent/Sources/SplunkAgent/Agent/AppState/NoOpAppStateManager.swift
SplunkAgent/Sources/SplunkAgent/Agent/Configuration/Models/AgentConfiguration+Empty.swift
SplunkAgent/Sources/SplunkAgent/Agent/Modules/SplunkRum+AppStart.swift
SplunkAgent/Sources/SplunkAgent/Agent/Modules/SplunkRum+Modules.swift
SplunkAgent/Sources/SplunkAgent/Agent/Session/NoOpSession.swift
SplunkAgent/Sources/SplunkAgent/Agent/SplunkRum+AppStart.swift
SplunkAgent/Sources/SplunkAgent/Agent/SplunkRum+Modules.swift
SplunkAgent/Sources/SplunkAgent/Agent/User/NoOpUser.swift
SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Public API/API-1.0-Sensitivity+UIView.swift
SplunkAgent/Sources/SplunkAgent/Public API/SplunkRum.swift
SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-AgentTests.swift

This PR implements the non-operational agent instance. 
Initial shared instance is initialized statically with non-operational variants of respective parameters. Install method performs checks, if all pass, full agent instance is created and assigned to the agent's singleton instance. 
This PR also refactors the SplunkRum class a bit as it was becoming too long.

DEMRUM-1635: Implement non operational agent instance

---

Package.swift
SplunkAgent/Tests/SplunkAgentTests/Agent/Events/EventsTests.swift
SplunkAgent/Tests/SplunkAgentTests/Public API/Modules/SessionReplay/API-1.0-TypeConversions.swift
TargetWrappers/CiscoDiskStorageWrapper/Sources/Empty.swift
TargetWrappers/CiscoEncryptionWrapper/Sources/Empty.swift
TargetWrappers/CiscoInstanceManagerWrapper/Sources/Empty.swift
TargetWrappers/CiscoInteractionsWrapper/Sources/Empty.swift
TargetWrappers/CiscoLoggerWrapper/Sources/Empty.swift
TargetWrappers/CiscoRuntimeCacheWrapper/Sources/Empty.swift
TargetWrappers/CiscoSessionReplayWrapper/Sources/Empty.swift
TargetWrappers/CiscoSwizzlingWrapper/Sources/Empty.swift

This PR brings in the implementation of Session Replay dependencies as binary targets.
Implementation details:
- The new binary targets are defined in a separate `registry` for easy enhancement and updates
- They require a "wrapping" target mechanism to properly resolve their dependency trees. The wrapping targets require their own folder structures, including empty stub files for the compiler. These are **not** added to the project files, as they are not relevant there
- The package still retains the functionality to link SR as either a remote or local package (repository) dependency
- The decision whether use binary targets or repository dependency (e.g. `DependencyResolutionStrategy`) is controlled using a set of `environment variables`
- All of the variables and their usage are …

DEMRUM-2084: Implement Session Replay modules as binary target dependencies

---

Package.swift
README.md
SplunkCrashReports/Sources/SplunkCrashReports/CrashReports.swift

- Using PLCrashReporter from Github rather than the internal version
- Added a separate on device folder to hold the crash reports, to avoid conflict with other instances (Firebase etc.)
- This folder is currently called 'SplunkCrashReports'
- Switched out SPLKPLCrashReporter from the build.
Please note: Left SplunkCrashReporter in place in the project. Code is not used and can be removed once testing is complete.

DEMRUM-970 Update to PLCrashReporter

---

Applications/DevelApp/DevelApp/DevelAppApp.swift
SplunkAgent/Sources/SplunkAgent/Agent/Configuration/Models/AgentConfigurationProtocol.swift
SplunkAgent/Sources/SplunkAgent/Agent/Modules/SplunkRum+AppStart.swift
SplunkAgent/Sources/SplunkAgent/Agent/Sampling/Session Sampling/DefaultAgentSessionSampler.swift
SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-AgentConfiguration.swift
SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-RuntimeState.swift
SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-SessionState.swift
SplunkAgent/Sources/SplunkAgent/Public API/Model/API-1.0-SessionConfiguration.swift
SplunkAgent/Sources/SplunkAgent/Public API/Model/API-1.0-UserConfiguration.swift
SplunkAgent/Sources/SplunkAgent/Public API/Model/API-1.0-UserTrackingMode.swift
SplunkAgent/Sources/SplunkAgent/Public API/SplunkRum.swift
SplunkAgent/Tests/SplunkAgentTests/Agent/Sampling/DefaultAgentSessionSamplerTests.swift
SplunkAgent/Tests/SplunkAgentTests/Agent/State/RuntimeStateTests.swift
SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-ConfigurationTests.swift
SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-StateTests.swift
SplunkAgent/Tests/SplunkAgentTests/Testing Support/Builders/ConfigurationTestBuilder.swift

This PR combines the `DEMRUM-2090` and `DEMRUM-2091` tasks into a single API-changing PR.
It also updates all related logic in the Agent, and implements additional test cases for the `user` configuration.

DEMRUM-2090: Implement UserConfiguration and SessionConfiguration

---

Applications/DevelApp/DevelApp.xcodeproj/project.pbxproj
Applications/DevelApp/DevelApp/CustomTrackingDemoView.swift
Applications/DevelApp/DevelApp/HelperViews.swift
Applications/DevelApp/DevelApp/ObjC/DevelApp-Bridging-Header.h
Applications/DevelApp/DevelApp/ObjC/ObjCExceptionHelper.h
Applications/DevelApp/DevelApp/ObjC/ObjCExceptionHelper.m
SplunkAgent/Sources/SplunkAgent/Public API/SplunkRum.swift

Improve error tracking api calls in DevelApp
- Add sample attributes to each error
- Add missing stack trace to Error and NSException (for NSError it already worked)
- Add Objective-C code to generate and handle an NSException
Triggering a real NSException gives a more  accurate reflection of real usage where we take content from the callStackSymbols property to populate the stack trace for NSException tracking.
We use Objective-C for generating the exception and this requires that we add bridging header to the DevelApp project.

DEMRUM-861: fill out error tracking demo calls

---

Package.swift

This PR updates the Session Replay package registry with CI-built and signed binaries, unified on version `1.0.6`.
This update should allow all developers to test the builds in real-world scenarios (e.g. on real devices) and also makes the Agent ready for release from the Session Replay linking perspective.

DEMRUM-2198: Update Session Replay binary artifacts

---

SplunkAgent/Sources/SplunkAgent/Agent/Events/Events/SessionReplayDataEvent.swift
SplunkAgent/Tests/SplunkAgentTests/Agent/Events/EventsTests.swift
SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-ConfigurationTests.swift
SplunkAgent/Tests/SplunkAgentTests/Testing Support/Builders/SessionReplayTestBuilder.swift

**Changes:**
-  Added the `segmentMetadata` attribute to the Session Replay log.

DEMRUM-2288: Add segmentMetadata attribute to Session Replay

---

SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-EndpointConfiguration.swift
SplunkAgent/Sources/SplunkAgent/Public API/Deprecated/Model/API-1.0-SplunkRumBuilder.swift
SplunkAgent/Sources/SplunkAgent/Public API/Model/API-1.0-AgentConfigurationError.swift
SplunkAgent/Sources/SplunkAgent/Public API/Model/API-1.0-MutableAttributes.swift

Minimal set of updates adding docc comments to public APIs that were missing them.
This does not address all consistency issues in all docc in the codebase; it only fills in gaps.

DEMRUM-1791: add docc comments to public apis that were missing them.

---

Package.swift
SplunkOpenTelemetryBackgroundExporter/Sources/SplunkOpenTelemetryBackgroundExporter/Exporters/metric/OTLPBackgroundHTTPMetricExporter.swift

This PR fixes (anchors) the opentelemtry-swift package dependency to the latest released version. The dependency had been anchored to `main` branch in order to support buildability to visionOS.

DEMRUM-2819: Fix opentelemetry-swift package dependency version

---

SplunkAgent/Sources/SplunkAgent/Public API/API-1.0-AgentConfiguration.swift

Added DocC comments for public properties in AgentConfiguration.

DEMRUM-2937: add missing docc for agentconfiguration properties

---

SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentationIgnoreURLs.swift
SplunkNetwork/Tests/SplunkNetworkTests/SplunkNetworkTests.swift

Update Network Attributes to new semantics
- update content_length attributes
- update url attributes
- update scheme attribute
- add support to remove obsolete keys from OTel instrumentation
- update unit tests

DEMRUM-2428: Update Network Span Attributes

---

SplunkInteractions/Sources/SplunkInteractions/Module/Interactions.swift
SplunkInteractions/Tests/SplunkInteractionsTests/SplunkInteractionsTests.swift

After retest and consultation with Pavel this re-enable focus interactions. Its working as expected.

DEMRUM-2760: Enable focus interaction

---

SplunkAgent/Sources/SplunkAgent/Agent/Events/Event Manager/DefaultEventManager.swift
SplunkAgent/Tests/SplunkAgentTests/Testing Support/Builders/SessionReplayTestBuilder.swift

This PR updates the scriptInstanceId parameter, which is used in a session replay data event as a required attribute. This PR updates the attribute so that it's based on a sessionId, by making it a 16 character substring of a sessionId.

DEMRUM-3131: Update scriptInstanceId parameter

---

Package.swift
SplunkAgent/Sources/SplunkAgent/Agent/Modules/Pool/DefaultModulesPool.swift
SplunkAgent/Sources/SplunkAgent/Agent/Modules/SplunkRum+Modules.swift
SplunkAppState/Sources/SplunkAppState/AppStateModule+Notifications.swift
SplunkAppState/Sources/SplunkAppState/AppStateModule.swift
SplunkAppState/Sources/SplunkAppState/Destination/AppStateDestination.swift
SplunkAppState/Sources/SplunkAppState/Destination/OTelDestination.swift
SplunkAppState/Sources/SplunkAppState/Model/AppStateType.swift
SplunkAppState/Sources/SplunkAppState/Module/AppStateConfiguration.swift
SplunkAppState/Sources/SplunkAppState/Module/AppStateModule+Module.swift
SplunkAppState/Sources/SplunkAppState/Module/AppStateRemoteConfiguration.swift
SplunkAppState/Tests/SplunkAppStateTests/AppStateModuleTests.swift
SplunkAppState/Tests/Support/MockDestination.swift

This PR implements app state handling and sending otel event based on:
[ticket DEMRUM-2793]([DEMRUM-2793](https://splunk.atlassian.net/browse/DEMRUM-2793))
[DOC](https://splunk.atlassian.net/wiki/x/7h2SMfs)
legacy agent:
new results:

DEMRUM-2793: Implement AppState module

---

Package.swift

This PR fixes a bug in Package manifest, where the SplunkCommon target did not import OpenTelemetryApi. This caused all tests to fail to build.

NO-TICKET: Fix OpenTelemetryApi import in SplunkCommon target

---

SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameTicker.swift
SplunkSlowFrameDetector/Tests/SplunkSlowFrameDetectorTests/SplunkSlowFrameDetectorTests.swift

First of two PRs that are targeting the task/DEMRUM-782-sfd-tests-pr0 branch.
This adds the foundational pieces needed to unit test the SlowFrameDetector. This is a non-functional, additive change.
* Introduces the SlowFrameTicker protocol to abstract CADisplayLink.
* Adds a MockTicker for simulating frame events in tests.
* Adds a MockDestination for capturing reported data in tests.

DEMRUM-782: introduce test abstractions and mocks

---

SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/Destination/OTelDestination.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/Destination/SlowFrameDetectorDestination.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameDetectorState.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameTicker.swift
SplunkSlowFrameDetector/Tests/SplunkSlowFrameDetectorTests/SplunkSlowFrameDetectorTests.swift

* Observes `appWillTerminateNotification` to flush buffered data.
* Converts the `SlowFrameDetectorDestination` protocol to async.
* Makes destination types public to support instantiation from the convenience `init`.
* Adds DocC comments to all module components.

DEMRUM-782: flush pending data on app termination

---

SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/Destination/OTelDestination.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/Destination/SlowFrameDetectorDestination.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameDetectorState.swift
SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameTicker.swift
SplunkSlowFrameDetector/Tests/SplunkSlowFrameDetectorTests/SplunkSlowFrameDetectorTests.swift

* Adds unit tests for slow frame detection.
* Includes tests for:
- Correctly identifying a slow frame.
- Correctly identifying a slow frame at the boundary.
- Ignoring normal-speed frames.
- Ignoring the very first frame.
* Adds `MockTicker` and `MockDestination` to the test suite.

DEMRUM-782: add slow frame tests

---

SplunkCommon/Sources/SplunkCommon/Span/Span+Extensions.swift
SplunkCommon/Tests/SplunkCommonTests/Testing Support/SpanExtensionsTests.swift

- Update calls in Span+Extensions.swift
- Add Unit tests for the extension functions
Build and confirm there are no deprecation warnings.

DEMRUM-3263: Remove deprecation warnings
