- README.md
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
- SplunkRumWorkspace/SplunkRum/SplunkRum/UIInstrumentation.swift
Refactor event subscription to make this easier.
> Add showVCInstrumentation for ViewController showing events.

- SplunkRumWorkspace/SplunkRum/SplunkRum/AppLifecycle.swift
- SplunkRumWorkspace/SplunkRumWorkspace.xcworkspace/xcshareddata/swiftpm/Package.resolved
- properly nil out active span to produce more than one (!)
- change name of component to app-lifecycle
- remove debug printout
> Several small lifecycle fixes

- README.md
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
- SplunkRumWorkspace/SplunkRum/SplunkRum/UIInstrumentation.swift
- Use UINavigationController's visible or top VC for screen name
- Create (optional) spans from setScreenName
> More UI fixes

- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
- SplunkRumWorkspace/SplunkRum/SplunkRumTests/TestUtils.swift
method/function to check if the library has been initialized
> Feature/Apmi-2899 method/function to check if the library has been initialized

- SplunkRumWorkspace/SplunkRum/SplunkRum/ScreenName.swift
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
Changes in screenname and splunkrum
> feature/APMI-2820 iOS crash does not retain old screen name

- .gitignore
- SplunkRumWorkspace/SplunkRum/SplunkRum/AppLifecycle.swift
- SplunkRumWorkspace/SplunkRum/SplunkRum/Session.swift
After the application is in the background for 15min a new rumSessionId will be created upon reopening the app.
> APMI 2307: Implements a 15min session timeout

- SplunkRumWorkspace/SplunkRum/SplunkRum/SpanDb.swift
https://www.sqlite.org/wal.html
> feat: enable WAL mode for span db

- SplunkRumWorkspace/SplunkRum/SplunkRum.xcodeproj/project.pbxproj
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
- SplunkRumWorkspace/SplunkRum/SplunkRumTests/SpanTests.swift
Adds a convenience function to SplunkRum to report an event.  Matches this function from the Android SDK https://github.com/signalfx/splunk-otel-android/blob/main/splunk-otel-android/src/main/java/com/splunk/rum/SplunkRum.java#L197
> Adds reportEvent function to SplunkRum

- CHANGELOG.md
- SplunkRumWorkspace/SmokeTest/SmokeTestUITests/SmokeTestUITests.swift
Adding a changelog file as required here.  https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md.
> Adds changelog markdown file

- CHANGELOG.md
Updates the changelog with 0.11.1 changes.
> Updates changelog with 0.11.1 changes

- README.md
> Updating gdi spec readme badge

- SplunkOtel.podspec
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRum.swift
- SplunkRumWorkspace/SplunkRum/SplunkRum/SplunkRumBuilder.swift
Adding back in option for showVCInstrumentation
> Adding option for showVCInstrumentation into SplunkBuilder

- README.md
> Fix gdi spec readme badge

- SplunkRumWorkspace/SplunkRum/SplunkRum/LimitingExporter.swift
This increases the maximum attribute field length to 32768 bytes
> Update MAX_ATTRIBUTE_LENGTH to 32Kb

- SplunkAgent/Sources/SplunkAgent/Agent/Session/DefaultSession.swift
- SplunkAgent/Sources/SplunkAgent/Extensions/String+HexID.swift
- SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
- SplunkAgent/Tests/SplunkAgentTests/Agent/Events/EventsTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Agent/Session/DefaultSessionTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Extensions/HexIDTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/Modules/SessionReplay/API-1.0-TypeConversions.swift
- SplunkAgent/Tests/SplunkAgentTests/Testing Support/Validators/HexIDValidator.swift
This PR updates session timeout and max duration, implements hex encoded session id, and makes tests buildable.
> DEMRUM-1043: Update session logic

- Splunk.xcworkspace/contents.xcworkspacedata
- SplunkAgent/Sources/SplunkAgent/Agent/Modules/Pool/DefaultModulesPool.swift
- SplunkAgent/Sources/SplunkAgent/Agent/State/DefaultSharedState.swift
- SplunkAgent/Sources/SplunkAgent/Public API/SplunkRum.swift
- SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
- SplunkAppStart/.gitignore
- SplunkAppStart/.swiftpm/xcode/xcshareddata/xcschemes/SplunkAppStart.xcscheme
- SplunkAppStart/.swiftpm/xcode/xcshareddata/xcschemes/SplunkAppStartTests.xcscheme
- SplunkAppStart/Package.swift
- SplunkAppStart/Sources/SplunkAppStart/AppStart+Notifications.swift
- SplunkAppStart/Sources/SplunkAppStart/AppStart+ProcessStart.swift
- SplunkAppStart/Sources/SplunkAppStart/AppStart.swift
- SplunkAppStart/Sources/SplunkAppStart/Destination/AppStartDestination.swift
- SplunkAppStart/Sources/SplunkAppStart/Destination/DebugDestination.swift
- SplunkAppStart/Sources/SplunkAppStart/Destination/OTelDestination.swift
- SplunkAppStart/Sources/SplunkAppStart/Module/AppStart+Module.swift
- SplunkAppStart/Sources/SplunkAppStart/Module/AppStartConfiguration.swift
- SplunkAppStart/Sources/SplunkAppStart/Module/AppStartRemoteConfiguration.swift
- SplunkAppStart/Tests/SplunkAppStartTests/AppStartTests+CheckType.swift
- SplunkAppStart/Tests/SplunkAppStartTests/AppStartTests+Notifications.swift
- SplunkAppStart/Tests/SplunkAppStartTests/AppStartTests.swift
- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
- SplunkOpenTelemetry/Package.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Resources/Resource+AgentResources.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Trace Processor/OTLPTraceProcessor.swift
- SplunkSharedProtocols/Sources/SplunkSharedProtocols/Agent/AgentSharedState.swift
This PR merges app start feature branch into the next gen branch.
> Merge feature/app-start into feature/next-gen

- SplunkRumWorkspace/SplunkRum/SplunkRum/OpenTelemetry/OpenTelemetryApi/Trace/Span.swift
Address contributing guidelines for #256
> Fix == for Span(s) type to Self #256

- Package.swift
- SplunkAgent/SplunkAgent.xcodeproj/project.pbxproj
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Log Event Processor/OTLPLogEventProcessor.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Stdout Exporters/SplunkStdoutLogExporter.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Stdout Exporters/SplunkStdoutSpanExporter.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Trace Processor/OTLPTraceProcessor.swift
This PR implements stdout Logs and Spans exporters.
> DEMRUM-1425: Stdout exporters

- SplunkNetwork/Sources/SplunkNetwork/Extensions/InternalLoggerConfiguration+Defaults.swift
- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation+Module.swift
- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentationConfig.swift
- Updated code to remove Lint errors
> DEMRUM-952 Network Module Lint Checks

- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
Added code to detect "server-timing" headers
Parse header to detect traceId and spanId
Add same to span attributes as link.traceId and link.spanId
> DEMRUM-868 Add server-timing attributs to span

- Package.swift
- SplunkInteractions/Sources/SplunkInteractions/Module/SplunkInteractions+Module.swift
- SplunkInteractions/Sources/SplunkInteractions/Module/SplunkInteractionsConfiguration.swift
- SplunkInteractions/Sources/SplunkInteractions/Module/SplunkInteractionsRemoteConfiguration.swift
- SplunkInteractions/Sources/SplunkInteractions/SplunkInteractions.swift
- SplunkInteractions/Tests/SplunkInteractionsTests/SplunkInteractionsTests.swift
- SplunkLogger/Sources/SplunkLogger/Configuration/Extensions/InternalLoggerConfiguration+Defaults.swift
Only module creation, final implementation with sending interaction event will be handled in DEMRUM-1730
> DEMRUM-854 SplunkInteractions

- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentationIgnoreURLs.swift
Update the IgnoreURLs class to conform to Codable for use in Configuration
> DEMRUM-2068 Add Codable to IgnoreURLs

- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
Repaired a type in the network delegate inclusion list.
> DEMRUM-2138 Update Network Delegate List

- SplunkAgent/Sources/SplunkAgent/Utils/Info/SystemInfo.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Resources/Resource+AgentResources.swift
Platform team will finish device model translation on backend. Based on Aditi's comment https://splunk.slack.com/archives/C07PANLTWG1/p1745350583791159
> DEMRUM-1401: Fix resources

- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
Added component = http to each network span
> DEMRUM-2354 Added component=http to span

- Applications/AgentTestApp/AgentTestApp/AppDelegate.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Model Conversions/RecordingMask+Conversions.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Model Conversions/RenderingMode+Conversions.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Model Conversions/Status+Conversions.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Proxies/Module/SessionReplay.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Proxies/Non-Operational/SessionReplayNonOperational+Preferences.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Proxies/Non-Operational/SessionReplayNonOperationalState.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Public API/API-1.0-SessionReplayModule.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Public API/Model/API-1.0-RenderingMode.swift
- SplunkAgent/Sources/SplunkAgent/Public API/Modules/Session Replay/Public API/Model/API-1.0-SessionReplayStatus.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/API-1.0-ConfigurationTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/Modules/SessionReplay/API-1.0-ModuleProxyTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/Modules/SessionReplay/API-1.0-NonOperationalProxyTests.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/Modules/SessionReplay/API-1.0-TypeConversions.swift
- SplunkAgent/Tests/SplunkAgentTests/Testing Support/Builders/SessionReplayTestBuilder.swift
**Changes:**
- Added missing APIs for the Session Replay module.
> DEMRUM-2399: Session Replay API

- SplunkInteractions/Sources/SplunkInteractions/Module/InteractionsConfiguration.swift
Adds docc and public init in interactions configuration
> NO-TICKET: Fix public init in interactions configuration

- SplunkAgent/Sources/SplunkAgent/Agent/Modules/SplunkRum+Modules.swift
- SplunkAgent/Tests/SplunkAgentTests/Public API/Deprecated/API-1.0-SplunkRumBuilderTests.swift
- SplunkInteractions/Sources/SplunkInteractions/Module/InteractionsConfiguration.swift
**Changes:**
- The default sensitivity for the `WKWebView` class in Session Replay has been turned off.
> DEMRUM-2685: Turn off the default sensitivity for WKWebView

- SplunkInteractions/Sources/SplunkInteractions/Module/Interactions.swift
- SplunkInteractions/Tests/SplunkInteractionsTests/SplunkInteractionsTests.swift
Filter out focus interactions in agent
> DEMRUM-2690: Remove focus from interactions

- SplunkCrashReports/Sources/SplunkCrashReports/CrashReports.swift
Injected actual crash timestamp into span.timestamp
> NO-TICKET: Inject crash timestamp into span

- Applications/DevelApp/DevelApp/CustomTrackingDemoView.swift
- SplunkAppStart/Sources/SplunkAppStart/Destination/OTelDestination.swift
- SplunkCommon/Sources/SplunkCommon/Span/Span+Extensions.swift
- SplunkCrashReports/Sources/SplunkCrashReports/CrashReports.swift
- SplunkNavigation/Sources/SplunkNavigation/Navigation+Span.swift
- SplunkNetwork/Sources/SplunkNetwork/NetworkInstrumentation.swift
- SplunkNetworkMonitor/Sources/SplunkNetworkMonitor/Destination/OTelDestination.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Span Processors/OLTPAttributesSpanProcessor.swift
- SplunkOpenTelemetry/Sources/SplunkOpenTelemetry/Span Processors/OTLPGlobalAttributesSpanProcessor.swift
- SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/Destination/OTelDestination.swift
- Update Network Module
- Update AppStart Module
- Update Crash Report Module
- Update Navigation Module
- Update Network Monitor Module
- Update Span Processors
- Update Slow Frame Detector
Each of the above modules was modified as requested to clear attributes before adding them.  In some cases, it was not entirely clear that the treatment is required but given safety of doing it and recommendations it seemed ok to err on that side.  I can certainly undo any module's changes.
The change has been implemented in a span extension as recommended by Vaclav
> DEMRUM-2683: Update SetAttributes Usage

- README.md
Update README.md in preparation for 2.0.0 GA release
* Add a Table of Contents for improved navigation.
* Replace the "Features" list with a "Modules Overview" table.
* Add a section for Crash Symbolication and dSYM uploads.
* Add a section for Advanced Configuration options.
* Add a section with Common Usage Examples for key APIs.
* Add Session Replay privacy examples for masking sensitive data.
* Add a section for Objective-C usage and examples.
* Add an Upgrading guide for users moving from previous versions.
* Update and clarify the main initialization code example.
* Update the link to the official documentation website.
Note: GAI was used to create a draft that was subsequently customized or modified
> DEMRUM-2722: Update README.md in preparation for 2.0.0 GA release

- SplunkSlowFrameDetector/Sources/SplunkSlowFrameDetector/SlowFrameLogic.swift
Second of two PRs that are targeting the task/DEMRUM-782-sfd-tests-pr0 branch.
* Adds the new `SlowFrameLogic` actor.
* This new actor contains the frame analysis and reporting logic previously in `SlowFrameDetector`.
* The actor is not yet integrated or used by `SlowFrameDetector`.
> DEMRUM-782: isolate frame analysis logic

- README.md
- Fixed custom event tracking example
- Updated ObjC section 
Checklist items do not apply
View Readme.md file in markdown editor
> NO-TICKET: Fixes in README.md

- .github/actions/build-and-tests/action.yml
- .github/actions/build-and-tests/scripts/build.sh
- .github/actions/build-and-tests/scripts/neutralize-sdk.sh
- .github/actions/build-and-tests/scripts/prepare-scheme.sh
- .github/actions/build-and-tests/scripts/prepare-workspace.sh
- .github/actions/build-and-tests/scripts/resolve-destinations.sh
- .github/actions/build-and-tests/scripts/test.sh
- .github/workflows/develop_ci.yml
- .github/workflows/pr.yml
This PR adds more complex simulator devices checking and upload xcresults to codecov
> NO-TICKET: Upgrade PR checks
